# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datanode.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'datanode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tanode.proto\x12\x06gridfs\"6\n\x05\x43hunk\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05\x63rc32\x18\x03 \x01(\r\"$\n\tUploadAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\x04\x32p\n\nDataNodeIO\x12,\n\x06Upload\x12\r.gridfs.Chunk\x1a\x11.gridfs.UploadAck(\x01\x12\x34\n\x08\x44ownload\x12\x17.gridfs.DownloadRequest\x1a\r.gridfs.Chunk0\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datanode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_CHUNK']._serialized_start=26
  _globals['_CHUNK']._serialized_end=80
  _globals['_UPLOADACK']._serialized_start=82
  _globals['_UPLOADACK']._serialized_end=118
  _globals['_DOWNLOADREQUEST']._serialized_start=120
  _globals['_DOWNLOADREQUEST']._serialized_end=155
  _globals['_DATANODEIO']._serialized_start=157
  _globals['_DATANODEIO']._serialized_end=269
# @@protoc_insertion_point(module_scope)
