# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import master_pb2 as master__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in master_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ls = channel.unary_unary(
                '/gridfs.Master/Ls',
                request_serializer=master__pb2.LsRequest.SerializeToString,
                response_deserializer=master__pb2.LsResponse.FromString,
                _registered_method=True)
        self.Mkdir = channel.unary_unary(
                '/gridfs.Master/Mkdir',
                request_serializer=master__pb2.MkdirRequest.SerializeToString,
                response_deserializer=master__pb2.MkdirResponse.FromString,
                _registered_method=True)
        self.Rm = channel.unary_unary(
                '/gridfs.Master/Rm',
                request_serializer=master__pb2.RmRequest.SerializeToString,
                response_deserializer=master__pb2.RmResponse.FromString,
                _registered_method=True)
        self.Rmdir = channel.unary_unary(
                '/gridfs.Master/Rmdir',
                request_serializer=master__pb2.RmdirRequest.SerializeToString,
                response_deserializer=master__pb2.RmdirResponse.FromString,
                _registered_method=True)
        self.PlanWrite = channel.unary_unary(
                '/gridfs.Master/PlanWrite',
                request_serializer=master__pb2.PlanWriteRequest.SerializeToString,
                response_deserializer=master__pb2.PlanWriteResponse.FromString,
                _registered_method=True)
        self.PlanRead = channel.unary_unary(
                '/gridfs.Master/PlanRead',
                request_serializer=master__pb2.PlanReadRequest.SerializeToString,
                response_deserializer=master__pb2.PlanReadResponse.FromString,
                _registered_method=True)


class MasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mkdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rmdir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanWrite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanRead(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ls': grpc.unary_unary_rpc_method_handler(
                    servicer.Ls,
                    request_deserializer=master__pb2.LsRequest.FromString,
                    response_serializer=master__pb2.LsResponse.SerializeToString,
            ),
            'Mkdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Mkdir,
                    request_deserializer=master__pb2.MkdirRequest.FromString,
                    response_serializer=master__pb2.MkdirResponse.SerializeToString,
            ),
            'Rm': grpc.unary_unary_rpc_method_handler(
                    servicer.Rm,
                    request_deserializer=master__pb2.RmRequest.FromString,
                    response_serializer=master__pb2.RmResponse.SerializeToString,
            ),
            'Rmdir': grpc.unary_unary_rpc_method_handler(
                    servicer.Rmdir,
                    request_deserializer=master__pb2.RmdirRequest.FromString,
                    response_serializer=master__pb2.RmdirResponse.SerializeToString,
            ),
            'PlanWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanWrite,
                    request_deserializer=master__pb2.PlanWriteRequest.FromString,
                    response_serializer=master__pb2.PlanWriteResponse.SerializeToString,
            ),
            'PlanRead': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanRead,
                    request_deserializer=master__pb2.PlanReadRequest.FromString,
                    response_serializer=master__pb2.PlanReadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gridfs.Master', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gridfs.Master', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Master(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridfs.Master/Ls',
            master__pb2.LsRequest.SerializeToString,
            master__pb2.LsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mkdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridfs.Master/Mkdir',
            master__pb2.MkdirRequest.SerializeToString,
            master__pb2.MkdirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridfs.Master/Rm',
            master__pb2.RmRequest.SerializeToString,
            master__pb2.RmResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rmdir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridfs.Master/Rmdir',
            master__pb2.RmdirRequest.SerializeToString,
            master__pb2.RmdirResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridfs.Master/PlanWrite',
            master__pb2.PlanWriteRequest.SerializeToString,
            master__pb2.PlanWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanRead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gridfs.Master/PlanRead',
            master__pb2.PlanReadRequest.SerializeToString,
            master__pb2.PlanReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
